<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>Mooseware.PatchPal</RootNamespace>
    <Company>Mooseware</Company>
    <Description>Video Patch and Matrix Configuration Planner</Description>
    <Copyright>Copyright © Mooseware Ltd 2023</Copyright>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <ApplicationIcon>Resources\PatchPal_Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="XmlFileHandler.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\PatchPal_Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\PatchPal_Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Dlls\AtemApi.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Dlls\Interop.BMDSwitcherAPI.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="HardwiredConfiguration.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="PatchConfiguration.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\PatchPal_Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dlls\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AtemApi">
      <HintPath>Dlls\AtemApi.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
